spring.application.name=Skill-9_GlobalExceptionHandlingUsing_ControllerAdvice
spring.datasource.url=jdbc:mysql://localhost:3306/performance_schema
spring.datasource.username=root
spring.datasource.password=ujjawal3269
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
